-- CREATE DATABASE Login_App;

-- use Login_App;

-- CREATE TABLE USERS(
--    ID INT AUTO_INCREMENT PRIMARY KEY,
--    USERNAME VARCHAR(50) NOT NULL,
--    PASSWORD VARCHAR(255) NOT NULL
-- );
use Login_App;
-- INSERT INTO  USERS (USERNAME,PASSWORD) VALUES('Irfan','Irfan@123');

SELECT *from users;